name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17
      - name: Release
        env:
          GOPROXY: proxy.golang.org
        run: go list -m "github.com/mhaii/go-pihole@${GITHUB_REF#refs/*/}"
